#include "Timestamp.idl"

struct Localization
{
    uint32    seq;

    Timestamp  stamp;

    uint8     status;

    double    longitude;
    double    latitude;
    double    altitude;
    double    headingAngle;
    double    pitchAngle;
    double    rollAngle;
};

struct Mapdata
{
    unsigned char* data;
    int width;
    int height;
    bool isChanged;
};